global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # KYC Service metrics
  - job_name: 'kyc-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kyc-service:8080']
    scrape_interval: 10s

  # Dashboard Service metrics (Laravel)
  - job_name: 'dashboard-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['dashboard-service:8000']
    scrape_interval: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # MinIO metrics
  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['minio:9000']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']